### ISSUE TITLE
MoSH Support?

### ISSUE THREAD

**Issue by FelicianoTech** [akerl/hss#33]
Would MoSH support be something doable for HSS?

Particularly because currently I have a few servers behind a NAT where I'm using a customer SSH port as well as a custom MoSH port range. HSS magic would be awesome.

**Comment by akerl** [comment]
I've not used MoSH personally, but HSS is basically just doing regex magic on the first thing that looks like a hostname.

Right now, it hardcodes "ssh " as the beginning of the thing it executes, but that's easy enough to change:

https://github.com/akerl/hss/blob/master/bin/hss#L19

I'd probably make the SSH_COMMAND configurable in the .hss.yml, and have HSS_DEBUG just prepend an echo to it.

Would having it run `mosh {long_form_from_config_file}` work?

**Comment by akerl** [comment]
Released 1.0.1 that adds HSS_COMMAND support. Let me know if that doesn't solve this

**Comment by FelicianoTech** [comment]
Awesome. How does that get pushed to the Gem installer?

**Comment by akerl** [comment]
Well, it works better if I actually cut the release. v1.0.1 released to rubygems. Should just be a quick `gem update hss` to get the new one

**Comment by FelicianoTech** [comment]
Thanks so much man.
