### ISSUE TITLE
Won't Execute over POSH/Windows Terminal

### ISSUE THREAD

**Issue by asianwaste** [akerl/hss#44]
I want to get HSS to work in a windows environment.  I was able to install ruby and I can gem the script over but it doesn't want to run.  

```
    PS C:\Users\username> gem install hss
    Successfully installed hss-1.0.1
    Parsing documentation for hss-1.0.1
    Done installing documentation for hss after 0 seconds
```

I believe I have made the symbolic link to a config file correctly which would be the equivalent to your installation step:

    `New-Item -ItemType SymbolicLink -Path "C:\Users\username\.hss.yml" -Target "C:\Users\username\hss-config\admin_config.yml"`

However I don't think that's related to the problem (yet).  Although it is installed and my environment acknowledges the application, it will execute but returns error citing missing paths:

```
    PS C:\Users\username> hss help
    C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:57:in `rescue in load_config': Failed to load config:  (RuntimeError)
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:51:in `load_config'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:29:in `initialize'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/bin/hss:5:in `new'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/bin/hss:5:in `<top (required)>'
    from C:/Ruby32-x64/bin/hss:32:in `load'
    from C:/Ruby32-x64/bin/hss:32:in `<main>'
    C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:53:in `read': No such file or directory @ rb_sysopen - C (Errno::ENOENT)
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:53:in `block in load_config'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:53:in `load_config'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:29:in `initialize'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/bin/hss:5:in `new'
    from C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/bin/hss:5:in `<top (required)>'
    from C:/Ruby32-x64/bin/hss:32:in `load'
    from C:/Ruby32-x64/bin/hss:32:in `<main>'
```

I can gem other scripts like rails and it is a painless install.  This one however is being troublesome.  What am I missing in my ruby or powershell config?  I think the problem might be that the output is using forward slash ( / ) notation but is not adapted to Microsoft's martian back slash ( \ )directory notation.  Could that be the cause?  Do you know how I can make fixes?

**Comment by akerl** [comment]
I think https://github.com/akerl/hss/commit/34260e2e98d2dc10566370c1d3482932543e936b should do it, but trying to chase down a Windows system to test on

**Comment by asianwaste** [comment]
I've downloaded the corrected files and replaced them.  My output has not changed.
Just to be sure, my symbolic link creation to the config file does seem to work.

```
PS C:\Users\username> New-Item -ItemType SymbolicLink -Path $home\.hss.yml -Target $home\hss-config\admin_config.yml


    Directory: C:\Users\username


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l          8/8/2023  10:08 AM              0 .hss.yml
```

and I do get the config file contents outputted when I test:
```
PS C:\Users\username> get-content .hss.yml
---
patterns:
    -   note: siphon boxes for obj storage migrations (prod)
    (rest of the lines redacted)
```
and $home seems to be in the right place
```
PS C:\Users\username> $home
C:\Users\username
```

I'm not sure if ruby itself needs some sort of configuration (new to ruby tbh) or if there is some sort of access blockage that powershell can't get through.  

This error output has me thinking it can't even get into my drive:
`C:/Users/username/.local/share/gem/ruby/3.2.0/gems/hss-1.0.1/lib/hss.rb:55:in `read': No such file or directory @ rb_sysopen - C (Errno::ENOENT)`

**Comment by akerl-unpriv** [comment]
Does it work w/o the symlink?

Also, can you share how you got Ruby installed on your system? I tried for a while last night and couldn't get it working. Gonna try some more later today.

**Comment by asianwaste** [comment]
https://www.geeksforgeeks.org/how-to-install-rubygems-in-windows/

I followed this.

I have also tried just copying my config file to my home directory and
renaming as appropriate.  I don't think the execution is even reaching that
directory.

**Comment by akerl** [comment]
I've figured it out. Not sure how I want to fix it yet, but now that I see it I'm shocked at how silly it is.

hss supports having multiple config files and stacking them. I added this feature forever ago, but I foolishly made the chaining work just like Linux's $PATH, where the items are delimited by colons ( https://github.com/akerl/hss/blob/main/lib/hss.rb#L55 )

Because the path on Windows starts with `C:`, this is parsing it as 2 different config files, `C` and `/Users/username/.hss.yml` which obviously doesn't work.

My gut is that I want to change the delimiter, but leave ":" as a supported delimiter on Linux only, to avoid a backwards-incompatible break. Lemme poke at it a bit, should have a change up shortly.

**Comment by akerl** [comment]
Give hss 1.1.0 a shot?

**Comment by asianwaste** [comment]
PS C:\Users\username> gem install hss --user
Fetching hss-1.1.0.gem
Successfully installed hss-1.1.0
Parsing documentation for hss-1.1.0
Installing ri documentation for hss-1.1.0
Done installing documentation for hss after 0 seconds
1 gem installed
PS C:\Users\username> hss help
How to use:
(what you type) -> (where it takes you)

**Comment by asianwaste** [comment]
It works!

Thank you so much for your time and help :)
